### ISSUE TITLE
quickstart.php for accessing data from spreadsheet of google

### ISSUE THREAD

**Issue by sushantwebmingo** [gsuitedevs/php-samples#15] opened 2018-07-31 07:22 UTC
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

```
Fatal error: Uncaught exception 'Google_Service_Exception' with message
'{
   "error":{
      "code":400,
      "message":"Unable to parse range: Class Data!A1:B",
      "errors":[
         {
            "message":"Unable to parse range: Class Data!A1:B",
            "domain":"global",
            "reason":"badRequest"
         }
      ],
      "status":"INVALID_ARGUMENT"
   }
}'
in
C:\xampp\htdocs\google_php_api\vendor\google\apiclient\src\Google\Http\REST.php:118 Stack trace: #0
C:\xampp\htdocs\google_php_api\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2
C:\xampp\htdocs\google_php_api\vendor\google\apiclient\src\Google\Task\Runner.php(181): call_user_func_array(Array, Array) #3
C:\xampp\htdocs\google_php_api\vendor\google\apiclient\src\Google\Http\REST.php(58): Google_Task_R in
C:\xampp\htdocs\google_php_api\vendor\google\apiclient\src\Google\Http\REST.php on line 118
```

## Expected Behavior
want to show all data of sheet

## Actual Behavior
want to show all data of sheet

## Steps to Reproduce the Problem

  1. install composer
  2. create credential.json
  3. token.json file created
4. above error is showing

## Specifications

  - PHP version (`php -v`): 5.4
  - OS (Windows):

**Comment by Fatimamohammad08** [comment] 2018-09-04 21:16
I get the same error whenever I try to change the spreadsheetId in order to view my spreadsheet but not the the one that's already in quickstart.php.

**Comment by Fatimamohammad08** [comment] 2018-09-04 21:17
Did you manage to display data from your own spreadsheet?

**Comment by grant** [comment] 2018-09-04 21:26
Hi @sushantwebmingo, what sample are you running? Are you sure that the Sheets quickstart was run without modifications?

I've formatted the issue. The error states the problem is with the range: `Class Data!A1:B`
See https://stackoverflow.com/questions/37893515/google-spreadsheet-api-400-error-bad-request-unable-to-parse-range

**Comment by Fatimamohammad08** [comment] 2018-09-04 21:43
@grant hey even i am getting the following error when i am trying to access my own spreadsheet:
Spreadsheet:
// https://docs.google.com/spreadsheets/d/1zJv6JEmeRnMj1So8jjzl6c9IsM2tViuUhII1ItQ4nDQ/edit
$spreadsheetId = '1zJv6JEmeRnMj1So8jjzl6c9IsM2tViuUhII1ItQ4nDQ';
print("$spreadsheetId");
$range = 'Class Data!A2:E';
print("\n$range");
$response = $service->spreadsheets_values->get($spreadsheetId, $range);
ERROR:
Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 400, "message": "Unable to parse range: test!A2:E", "errors": [ { "message": "Unable to parse range: test!A2:E", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } } in C:\xampp\htdocs\PhpProject1\scratch\google-api-php-client-2.2.2\src\Google\Http\REST.php:118 Stack trace: #0 C:\xampp\htdocs\PhpProject1\scratch\google-api-php-client-2.2.2\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 C:\xampp\htdocs\PhpProject1\scratch\google-api-php-client-2.2.2\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 C:\xampp\htdocs\PhpProject1\scratch\google-api-php-client-2.2.2\src\Google\Http\REST.php(58): Google_Task_Runner->run() #3 C:\xampp\htdocs\PhpProject1\scratch\google-ap in C:\xampp\htdocs\PhpProject1\scratch\google-api-php-client-2.2.2\src\Google\Http\REST.php on line 118

**Comment by grant** [comment] 2018-09-04 21:46
@Fatimamohammad08 It looks like you're using `"test!A2:E"`. The error states it is unable to parse this. Can you try using a range like `"A2:E2"`?

**Comment by Fatimamohammad08** [comment] 2018-09-05 06:29
@grant hey thanks for the help ! I had a question . 
is that possible to pull out only one record from google sheet according to the user ID that's used for authentication? 
so that i don't need to pull over the complete spreadsheet and do an if statement?

**Comment by grant** [comment] 2018-09-05 06:37
@Fatimamohammad08 It is not possible to get just one row or cell. You can sort the sheet and get a range which is the top value, but you can't retrieve a cell by ID.

https://stackoverflow.com/questions/38114591/is-it-possible-to-access-row-id-of-a-google-spreadsheet

That question doesn't relate to this issue though and may be better for StackOverflow.

**Comment by Fatimamohammad08** [comment] 2018-09-23 13:04
@grant Hello ! I wanted to know how can you fetch the data using a query? for example how would i get a row https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit from this if the student name is Alexander?

**Comment by sushantwebmingo** [comment] 2018-09-24 12:33
I can get particular data of given name by spreadsheet api but not by ther query. We can not apply query here.

**Comment by Fatimamohammad08** [comment] 2018-09-24 13:02
@sushantwebmingo so if I have a column as ID as my unique Id . Can;t I query like in SQL ? 
Because if I use his link below https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/gviz/tq?tqx=out:html&tq=select+A,B,C,D,E+where+A=%27Alexandra%27
it does get the data. but i am unable to understand how to make it work using php.

**Comment by grant** [comment] 2018-10-18 18:02
You cannot use Sheets like a SQL database or query like a database. Maybe you could try this option:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGetByDataFilter

Please use the issue tracker for generic issues as GitHub is used for existing code samples. You can still discuss here if you wish, but I'll close this issue.

**Closed by grant** 2018-10-18 18:02 UTC
