### ISSUE TITLE
I am getting "cURL error 60"

### ISSUE THREAD

**Issue by vibhajadwani** [gsuitedevs/php-samples#8] opened 2018-07-19 10:32 UTC
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\wamp\www\tripbuilder\google_sheet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by grant** [comment] 2018-07-24 03:56
@vibhajadwani Did following the link above solve the problem?

**Comment by erickoledadevrel** [comment] 2018-08-27 17:15
Yes, duplicate of #19.

**Closed by erickoledadevrel** 2018-08-27 17:15 UTC
